### ISSUE TITLE
Pointer Events support

### ISSUE THREAD

**Issue by patrickhlauke** [rafrex/detect-it#2]
> Note that Detect It v2 removed support for Pointer Events detection because they're just not relevant enough (only used by IE and Edge and not supported by React)

While I can't speak for React, it's not accurate anymore that PE are only in IE/Edge. Chrome stable shipped with PE on a few months ago, and chromium-based browsers now have PE as well (e.g. Samsung Internet, Opera...). Firefox are still working on their implementation, but it should ship in the coming months. See http://caniuse.com/#search=pointer%20events

**Comment by rafrex** [comment]
@patrickhlauke good to know, I've updated the readme to reflect this, however, I still don't find them relative enough to use in my projects because support is less than 60% (according to Can I Use), and most of what I'm building is in React. I do like the API and when support is >90% I'd probably switch (hopefully React will have support then), but currently I can't justify writing code for two different event systems in my projects.
