### ISSUE TITLE
hasMouse issue with Mozilla Firefox v53

### ISSUE THREAD

**Issue by pnarielwala** [rafrex/detect-it#4]
detect-it is showing the deviceType being touchOnly on the desktop Mozilla Firefox browser which definitely supports mouse events

**Comment by rafrex** [comment]
@pnarielwala I unable to reproduce this issue with Firefox v53 on a MacBook Pro running macOS Sierra (it registers as `mouseOnly` for me). What OS and hardware are you using? Does your device have a touch screen as well as a mouse?

**Comment by pnarielwala** [comment]
I'm running it on Windows 10 on a Lenovo T440s. My device does not have a touch screen which makes it weird that it shows 'touchOnly'. This is what I get from your live detection test:

deviceType: touchOnly
passiveEvents: true
hasMouse: false
hasTouch: true
maxTouchPoints: undefined
primaryHover: none
primaryPointer: coarse

Detect Hover:
hover: false
none: false
anyHover: false
anyNone: false

Detect Pointer:
fine: false
coarse: false
none: false
anyFine: false
anyCoarse: false
anyNone: false

Detect Touch Events:
hasApi: true
maxTouchPoints: undefined

Detect Passive Events:
hasSupport: true

**Comment by rafrex** [comment]
That is weird. There is a long standing issue of Firefox not implementing hover and point media queries which is why Detect Hover and Detect Pointer are all `false` https://bugzilla.mozilla.org/show_bug.cgi?id=1035774, but if it doesn't have a touch screen I'm surprised it's registering as though it does.

Can you run the following in your Firefox console (one at a time) and let me know the results, thanks:
`window.matchMedia('(-moz-touch-enabled: 0)').matches`
`window.matchMedia('(-moz-touch-enabled: 1)').matches`
`window.TouchEvent` this will either be a function or undefined
`'ontouchstart' in window`
`'ontouchend' in document`

**Comment by pnarielwala** [comment]
Sure here's what I got:

`window.matchMedia('(-moz-touch-enabled: 0)').matches = false`
`window.matchMedia('(-moz-touch-enabled: 1)').matches = true`
`window.TouchEvent = function ()`
`'ontouchstart' in window = true`
`'ontouchend' in document = true`

**Comment by rafrex** [comment]
Thanks. Even the Firefox specific `-moz-touch-enabled` is saying you have a touch screen. I feel like this may be a bug in Firefox's implementation on your hardware.

Do you know if this was an issue with Firefox v52 as well?

I'll consider adding Firefox browser sniffing as a fix, probably something like if it's Firefox and it supports touch events, then call it a hybrid (because I don't think there is anyway to tell the difference between Firefox running on your laptop or on an actual hybrid, like a Surface).
You have any thoughts or suggestions?

**Comment by rafrex** [comment]
@pnarielwala I fixed this (sort of) in v3, see #5. Basically, if it registers as `hasTouch` with no pointer and hover support, and it's not on an Android assume it's a `hybrid` device with a `mouse` `primaryInput` type (if it's on Android assume it's `touchOnly`).

I know this means that your device with Firefox will register as a `hybrid` even though it should be `mouseOnly`, but if Firefox is going to tell me it supports touch there's not much I can do about it because it might actually be running on a hybrid device, e.g. a Surface.

Essentially since it registers as `hybrid` you should set both mouse and touch listeners, and the `primaryInput` type of `mouse` means you can optimize the UI for mouse input. So your site should work just fine on Firefox on your mouse only device.

**Comment by pnarielwala** [comment]
@rafrex that will work! Thanks!
